project:
  type: website
  output-dir: docs

website:
  title: "BIO476 Evo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: acido.qmd
        text: Acidobacteriota
      - href: WREF.qmd
        text: Wind River Experimental Forest
      - href: ref.qmd
        text: References
   

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

