project:
  type: website
  output-dir: docs

website:
  title: "BIO476 Evo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd 
        text: About
      - href: labs.qmd
        text: Labs
      - href: project.qmd
        text: Project
      - href: presentation.qmd
        text: Presentation

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

